version: "3"

services:
  qdrant:
    image: qdrant/qdrant:${QDRANT_VERSION}
    restart: unless-stopped
    environment:
      - QDRANT_HOST=${QDRANT_HOST}
    ports:
      - ${QDRANT_PORT}:6333
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - wine
  
  fastapi:
    image: qdrant_wine_fastapi:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.onnxruntime
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${API_PORT}:8000
    depends_on:
      - qdrant
    volumes:
      - ./:/wine
    networks:
      - wine
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  qdrant_storage:

networks:
  wine:
    driver: bridge